package:
  name: icu
  version: 61.1

source:
  fn:  icu4c-61_1-src.tgz                                                             [unix]
  url: http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.tgz            [unix]
  md5: 68fe38999fef94d622bd6843d43c0615                                               [unix]

about:
  home: http://site.icu-project.org/
  license: MIT
