package:
  name: icu
  version: 65.1

source:
  fn:  icu4c-65_1-src.tgz                                                                   [unix]
  url: https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-src.tgz [unix]
  md5: d1ff436e26cabcb28e6cb383d32d1339                                                     [unix]

about:
  home: http://site.icu-project.org/
  license: MIT
