package:
  name: quantlib-python
  version: 1.12.1
  
source:
  git_url: https://github.com/lballabio/QuantLib-SWIG.git
  
requirements:
  build:
    - swig
    - python
  run:
    - python

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib-SWIG/blob/master/LICENSE.TXT
  summary: "QuantLib-Python: Python binding for QuantLib"
