package:
  name: quantlib-python
  version: 1.17
  
source:
  git_url: https://github.com/lballabio/QuantLib-SWIG.git
  
requirements:
  build:
    - swig >=4.0.1
    - python >=3.7
    - numpy >=1.17.2
  run:
    - python

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib-SWIG/blob/master/LICENSE.TXT
  summary: "QuantLib-Python: Python binding for QuantLib"
