package:
  name: boost
  version: 1.67.0

source:
  fn:  boost_1_67_0.tar.bz2
  url: https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.bz2
  md5: ced776cb19428ab8488774e1415535ab
requirements:
  build:
    - python
    - icu
    - bzip2          
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - icu
    - zlib

about:
  home: http://www.boost.org/
  license: https://www.boost.org/LICENSE_1_0.txt
