package:
  name: boost
  version: 1.72.0

source:
  fn:  boost_1_72_0.tar.bz2
  url: https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
  sha256: 59c9b274bc451cf91a9ba1dd2c7fdcaf5d60b1b3aa83f2c9fa143417cc660722
requirements:
  build:
    - python
    - icu
    - bzip2          
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - icu
    - zlib

about:
  home: http://www.boost.org/
  license: https://www.boost.org/LICENSE_1_0.txt
