package:
  name: quantlib
  version: 1.17
  
source:
  git_url: https://github.com/lballabio/QuantLib.git
  
requirements:
  build:
    - m4
    - automake
    - autoconf
    - libtool
    - boost
  run:

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib/blob/master/LICENSE.TXT
  summary: "QuantLib: A free/open-source library for quantitative finance"
