package:
  name: quantlib-python
  version: 1.12.1
  
source:
  git_url: https://github.com/lballabio/QuantLib-SWIG.git
  
requirements:
  build:
    - automake
    - autoconf
    - libtool
    - boost
  run:

about:
  home: http://www.quantlib.org/
  license: https://github.com/lballabio/QuantLib-SWIG/blob/master/LICENSE.TXT
  summary: "QuantLib-SWIG: language binding for QuantLib"
