package:
  name: psycopg2
  version: 2.7.4

source:
  git_url: https://github.com/psycopg/psycopg2.git
  patches:
    - have_openssl.patch

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - postgresql
  run:
    - python
    - openssl 1.0.2*
    - libpq

test:
  imports:
    - psycopg2
    - psycopg2._psycopg

about:
  home: http://initd.org/psycopg/
  license: LGPL, BSD-like, ZPL
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: http://initd.org/psycopg/docs/
  doc_source_url: https://github.com/psycopg/psycopg2/blob/master/doc/src/index.rst
  dev_url: https://github.com/psycopg/psycopg2/
