package:
  name: swig
  version: 4.0.1

source:
  fn: swig-4.0.1.tar.gz   [unix]
  url: http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz
  sha1: 3915d3ab537c171d6d086a8e93bfc545cebf6172

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - pcre
    - python
  run:
    - pcre
    
test:
  commands:
    - swig -help

about:
  home: http://www.swig.org/
  license: GPLv3
  summary: C/C++ parser code generator
