package:
  name: pcre
  version: 8.42

source:
  url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.42.tar.gz
  sha1: b3aec1f643d9701841e2f9d57ac121a7ff448fc8

requirements:
  build:
    - zlib
    - bzip2
  run:
    - zlib

about:
  home: http://www.pcre.org/
  license: 3-clause BSD License
  license_family: BSD
  summary: A set of functions that implement regular expression pattern matching
  description: |
    The PCRE library is a set of functions that implement regular expression
    pattern matching using the same syntax and semantics as Perl 5. PCRE has
    its own native API, as well as a set of wrapper functions that correspond
    to the POSIX regular expression API. The PCRE library is free, even for
    building proprietary software.
  doc_url: http://www.pcre.org/original/doc/html/
  dev_url: http://vcs.pcre.org/pcre2/
